### ISSUE TITLE
Cannot tag with ElasticSearch 2.2

### ISSUE THREAD

**Issue by wenzowski** [KnowledgeGarden/BacksideServletKS#17]
Need to fall back to using ElasticSearch 1.7

Have to tap to get that: `brew install Homebrew/homebrew-versions/elasticsearch17`

**Comment by wenzowski** [comment]
That gets us

```
$ elasticsearch -v
Version: 1.7.5, Build: 00f95f4/2016-02-02T09:55:30Z, JVM: 1.8.0_66
```

**Comment by OpenSherlock** [comment]
No clue what that means. ES is now up to 2.3.3 and the upgrades to the lower-level code TQElasticKnowledgeSystem require at least 2.3+

**Comment by wenzowski** [comment]
Thought I was documenting a known issue. Stack trace coming up.

**Comment by wenzowski** [comment]
This is exactly the same with ElasticSearch 2.3.3 as well.

Say I post the payload

```
{
      verb: 'FindProcessTag',
      sToken: '205121df-d032-49e8-93b8-95bd910ad742',
      uName: 'defaultadmin',
      lox: '8c694cc8-e7ce-48d1-bd09-8beef5ff6c3d',
      ListProperty: ['tag1', 'tag2'],
      Lang: 'en'
}
```

where sToken is valid and `lox` refers to a blogs post. This encodes as

```
/tm/%7B%22verb%22%3A%22FindProcessTag%22%2C%22sToken%22%3A%2236d1ed94-f4ef-4c63-abd0-33cf65a3a3d9%22%2C%22uName%22%3A%22defaultadmin%22%2C%22lox%22%3A%22e6472fce-3c77-4d4b-b8ed-d7882ebc0bad%22%2C%22ListProperty%22%3A%5B%22tag1%22%2C%22tag2%22%5D%2C%22Lang%22%3A%22en%22%7D
```

and BacksideServletKS responds with a 500 error and the payload

```
{"rMsg":"; ; ; JsonObject; ; ; JsonObject","rToken":""}
```

and emits the following trace in the logs

```
java.lang.UnsupportedOperationException: JsonObject
    at com.google.gson.JsonElement.getAsString(JsonElement.java:191)
    at io.searchbox.client.JestResult.setJsonObject(JestResult.java:105)
    at io.searchbox.action.AbstractAction.createNewElasticSearchResult(AbstractAction.java:70)
    at io.searchbox.action.SingleResultAbstractDocumentTargetedAction.createNewElasticSearchResult(SingleResultAbstractDocumentTargetedAction.java:16)
    at io.searchbox.action.SingleResultAbstractDocumentTargetedAction.createNewElasticSearchResult(SingleResultAbstractDocumentTargetedAction.java:9)
    at io.searchbox.client.http.JestHttpClient.deserializeResponse(JestHttpClient.java:131)
    at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:50)
    at org.topicquests.node.provider.Client.updateNode(Client.java:141)
    at org.topicquests.ks.tm.TQSystemDataProvider.updateNode(TQSystemDataProvider.java:257)
    at org.topicquests.ks.tm.SubjectProxyModel.relateExistingNodesAsPivots(SubjectProxyModel.java:329)
    at org.topicquests.backside.servlet.apps.tm.TagModel.addTagsToNode(TagModel.java:97)
    at org.topicquests.backside.servlet.apps.tm.TopicMapModel.findOrProcessTags(TopicMapModel.java:431)
    at org.topicquests.backside.servlet.apps.tm.TopicMapHandler.handlePost(TopicMapHandler.java:323)
    at org.topicquests.backside.servlet.apps.BaseHandler.executePost(BaseHandler.java:188)
    at org.topicquests.backside.servlet.apps.tm.TopicMapServlet.doPost(TopicMapServlet.java:44)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
    at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:256)
    at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:219)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:499)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by wenzowski** [comment]
When I revert to 1.7 everything goes smoothly. What specifically requires latest ElasticSearch?

**Comment by OpenSherlock** [comment]
Ok, that one requires some deep research. I need to replicate that on my end to see what happens. There have been a few subtle changes to ES specifications which might provoke that.

**Comment by wenzowski** [comment]
Ought to be fixed in latest release (0.6.1); will confirm.
